force-app/main/default/objects/Account/fields/Average_satisfaction_rating__c.field-meta.xml
<CustomField>
    <fullName>Average_satisfaction_rating__c</fullName>
    <description>The average rating of all the cases of an Account.</description>
    <label>Average satisfaction rating</label>
    <precision>2</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Case/fields/Satisfaction_rating__c.field-meta.xml
<CustomField>
    <fullName>Satisfaction_rating__c</fullName>
    <label>Satisfaction rating</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>1</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CaseHelper.cls
public with sharing class CaseHelper {
    public static void updateAccountRatingAfterCloseCase(List<Case> updatedCases) {
        Set<Id> accountIds = new Set<Id>();
        for (Case caseRecord : updatedCases) {
            if (caseRecord.Status == 'Closed') {
                accountIds.add(caseRecord.AccountId);
            }
        }
        List<Account> accountsToUpdate = [
                SELECT Average_satisfaction_rating__c, (
                        SELECT Satisfaction_rating__c
                        FROM Cases
                        WHERE Status = 'Closed'
                )
                FROM Account
                WHERE Id = :accountIds
        ];
        for (Account accountRecord : accountsToUpdate) {
            Double ratingOfAccount = 0;
            for (Case caseRecordForAccountAverageRating : accountRecord.Cases) {
                ratingOfAccount += Integer.valueOf(caseRecordForAccountAverageRating.Satisfaction_rating__c);
            }
            if (accountRecord.Cases.size() > 0) {
                accountRecord.Average_satisfaction_rating__c = ratingOfAccount / accountRecord.Cases.size();
            }
        }
        update accountsToUpdate;
    }
}